# Logistic regresion using Sckit Learn

In [2]:
import pandas as pd

In [14]:
adult_census = pd.read_csv('data/adult_data.csv')

In [15]:
adult_census = adult_census.drop(columns = "education-num")
#because education-num is redundant
adult_census.head()

,age,workclass,fnlwgt,education,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,25.0,b'Private',226802.0,b'11th',b'Never-married',b'Machine-op-inspct',b'Own-child',b'Black',b'Male',0.0,0.0,40.0,b'United-States',b'<=50K'
1,38.0,b'Private',89814.0,b'HS-grad',b'Married-civ-spouse',b'Farming-fishing',b'Husband',b'White',b'Male',0.0,0.0,50.0,b'United-States',b'<=50K'
2,28.0,b'Local-gov',336951.0,b'Assoc-acdm',b'Married-civ-spouse',b'Protective-serv',b'Husband',b'White',b'Male',0.0,0.0,40.0,b'United-States',b'>50K'
3,44.0,b'Private',160323.0,b'Some-college',b'Married-civ-spouse',b'Machine-op-inspct',b'Husband',b'Black',b'Male',7688.0,0.0,40.0,b'United-States',b'>50K'
4,18.0,b'?',103497.0,b'Some-college',b'Never-married',b'?',b'Own-child',b'White',b'Female',0.0,0.0,30.0,b'United-States',b'<=50K'

In [17]:
data, target = adult_census.drop(columns = "class"), adult_census["class"]

In [18]:
data.head()

,age,workclass,fnlwgt,education,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,25.0,b'Private',226802.0,b'11th',b'Never-married',b'Machine-op-inspct',b'Own-child',b'Black',b'Male',0.0,0.0,40.0,b'United-States'
1,38.0,b'Private',89814.0,b'HS-grad',b'Married-civ-spouse',b'Farming-fishing',b'Husband',b'White',b'Male',0.0,0.0,50.0,b'United-States'
2,28.0,b'Local-gov',336951.0,b'Assoc-acdm',b'Married-civ-spouse',b'Protective-serv',b'Husband',b'White',b'Male',0.0,0.0,40.0,b'United-States'
3,44.0,b'Private',160323.0,b'Some-college',b'Married-civ-spouse',b'Machine-op-inspct',b'Husband',b'Black',b'Male',7688.0,0.0,40.0,b'United-States'
4,18.0,b'?',103497.0,b'Some-college',b'Never-married',b'?',b'Own-child',b'White',b'Female',0.0,0.0,30.0,b'United-States'

In [19]:
target.head()

0    b'<=50K'
1    b'<=50K'
2     b'>50K'
3     b'>50K'
4    b'<=50K'
Name: class, dtype: object

In [27]:
data.dtypes

age               float64
workclass          object
fnlwgt            float64
education          object
marital-status     object
occupation         object
relationship       object
race               object
sex                object
capital-gain      float64
capital-loss      float64
hours-per-week    float64
native-country     object
dtype: object

In [28]:
numerical_columns = ["age", "capital-gain", "capital-loss", "hours-per-week"]
data[numerical_columns].head()

    age  capital-gain  capital-loss  hours-per-week
0  25.0           0.0           0.0            40.0
1  38.0           0.0           0.0            50.0
2  28.0           0.0           0.0            40.0
3  44.0        7688.0           0.0            40.0
4  18.0           0.0           0.0            30.0

In [29]:
data["age"].describe()

count    48842.000000
mean        38.643585
std         13.710510
min         17.000000
25%         28.000000
50%         37.000000
75%         48.000000
max         90.000000
Name: age, dtype: float64

In [30]:
data_numeric = data[numerical_columns]

In [31]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(data_numeric,target, random_state=42, test_size =0.25)

- Split the data and target into test and train.
- `random_state = 42` is for reproducibilty
- `test_size = 0.25` means 25% data is for test

In [32]:
data_test.shape

(12211, 4)

In [33]:
data_train.shape

(36631, 4)

In [34]:
target_train.shape

(36631,)

In [35]:
target_test.shape

(12211,)

In [37]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [40]:
model.fit(data_train,target_train)

LogisticRegression()

In [41]:
accuracy = model.score(data_test, target_test)

In [42]:
accuracy

0.8070592089099992